name: wazo-calld-application-external-media
namespace: sboily
version: 0.0.1
author: Sylvain Boily
display_name: Stream channel media to external application
min_wazo_version: 23.08
tags:
  - experimental
  - application
homepage: https://github.com/sboily/wazo-calld-application-external-media
